
application:
  name: "Latency Stats"
  home: target/

endpoints.enabled: true

server:
  tomcat:
    basedir: ${application.home}
    max-threads: 10
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
  port: 8084
  additionalHttpPorts: 8443


spring.datasource:
  url: "jdbc:mysql://latencystatsdb.cedako7zoc64.us-west-2.rds.amazonaws.com:3306/LatancyStatsServiceDB"
  username: "nathnael2"
  password: "NatMysql_AWS_19"
  hikari:
    connection-timeout: 60000
    maximum-pool-size: 5

swagger:
  service:
    version: "1.0"
    title: ${application.name}
    description: "Latency Stats Service"
    termsPath: ""
    email: "nalemu@expedia.com"
    licenceType: ""
    licencePath: ""

spring:
    jpa:
       databasePlatform: org.hibernate.dialect.MySQLDialect

logging:
  file: ${APP_LOGS:${application.home:target}/logs}/${application.name}.txt
  level:
    org.springframework: INFO
    com.expedia.www.cs.lds.cacheloader: INFO
    ROOT: ERROR


